app/models/patient.py
from app.extentions import db
from app.models import UserModel

class PatientModel(db.Model):
    __tablename__ = "patients"
    # id = db.Column(db.Integer, db.ForeignKey('users.id'), primary_key=True)
    
    
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), unique=True)

    # Mandatory fields
    phone_no = db.Column(db.String(15), nullable=False)
    age = db.Column(db.Integer, nullable=False)
    gender = db.Column(db.String(10), nullable=False)
    address = db.Column(db.String(255), nullable=False)
    
    # Optional fields
    height = db.Column(db.Float, nullable=True)
    weight = db.Column(db.Float, nullable=True)

    # __mapper_args__ = {
    #     'polymorphic_identity': 'patient'
    # }

    
    # # Define foreign key
    # patient_id = db.Column(db.Integer, db.ForeignKey('patients.id'), unique=True, nullable=False)

    # # Define back-reference to PatientModel
    # patient = db.relationship('PatientModel', back_populates='information')

  





# from flask_sqlalchemy import SQLAlchemy
# from flask_login import UserMixin

# class PatientModel(db.Model, UserMixin):
#     __tablename__ = "patients"
#     id = db.Column(db.Integer, primary_key=True)
#     fullname = db.Column(db.String(100), nullable=False)
#     email = db.Column(db.String(120), unique=True, nullable=False)
#     password = db.Column(db.String(60), nullable=False)

#     # Define one-to-one relationship with PatientInformationModel
#     information = db.relationship('PatientInformationModel', back_populates='patient', uselist=False, cascade='all, delete-orphan')

    # def __repr__(self) -> str:
    #     return f"User( '{self.fullname}','{self.email}','{self.information.age},'{self.information.gender}')"
    

 

app/patient/forms.py
from collections.abc import Mapping, Sequence
from typing import Any
from flask_wtf import FlaskForm
from wtforms import StringField,PasswordField,SubmitField,SelectField,FloatField,TextAreaField, ValidationError
from wtforms.validators import DataRequired,Length, Email, Optional,EqualTo,Regexp, ValidationError
from flask_wtf.file import FileField, FileAllowed

from flask_login import current_user

from app.models import PatientModel,UserModel


# Patient Registration Form
class PatientRegistrationForm(FlaskForm):
    full_name = StringField("Full Name",validators=[DataRequired(), Length(min=2, max=40)])
    email = StringField("Email",validators =[DataRequired(), Email()])
    password = PasswordField("Password",validators=[DataRequired(),Length(min=2, max=20)])
    confirm_password = PasswordField('Confirm Password',validators=[DataRequired(), EqualTo('password')])

    submit = SubmitField("Sign Up")
    
    # Emaiil validation in database
    def validate_email(self,email):
        patient = UserModel.query.filter_by(email=email.data,role="patient").first()
        if patient:
            raise ValidationError("Patient with this email is already registered.")

# Patient Login Form
class PatientLoginForm(FlaskForm):
    email = StringField("Email",validators =[DataRequired(), Email()])
    password = PasswordField("Password",validators=[DataRequired(),Length(min=2, max=20)])
    submit = SubmitField("Login")

# Patient Profile Update Form
class PatientProfileUpdateForm(FlaskForm):
    picture = FileField('Profile Picture', validators=[FileAllowed(['jpg', 'png'])])
    #mandatory fields
    phone_no = StringField('Phone Number', validators=[DataRequired(),Length(min=10, max=10, message='Mobile number must be 10 digits long'),Regexp(r'^[6789]\d{9}$', message='Invalid mobile number format')])
    age = FloatField("Age",validators=[DataRequired()])
    gender = SelectField("Gender",choices=[("male","Male"),("female","Female")],validators=[DataRequired()])
    address = TextAreaField("Adress",validators=[DataRequired(),Length(max=200)])

    #optional fields
    height = FloatField("Height",validators=[Optional()])
    weight =FloatField("Weight", validators=[Optional()])

    submit = SubmitField("Update Profile")

    # #email validation check
    # def validate_email(self, email):
    #     if email.data != current_user.email:
    #         user = UserModel.query.filter_by(email=email.data,role="patient").first()
    #         if user:
    #             raise ValidationError('That email is taken. Please choose a different one.')
class PatientGetResetLinkForm(FlaskForm):
    email = StringField("Email",validators =[DataRequired(), Email()])
    submit = SubmitField("Get Password Reset Link")
    
    # Emaiil validation in database
    def validate_email(self,email):
        patient = UserModel.query.filter_by(email=email.data,role="patient").first()
        if not patient:
            raise ValidationError("Patient with this email doesn't exist.")


class PatientResetPasswordForm(FlaskForm):
    password = PasswordField("Password",validators=[DataRequired(),Length(min=2, max=20)])
    confirm_password = PasswordField('Confirm Password',validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField("Reset Password")

app/patient/__init__.py
from flask import Blueprint

bp = Blueprint("patient",__name__)

from app.patient import routes

app/patient/routes.py
import datetime
from turtle import tilt, title
from flask import Flask,redirect,render_template,url_for,flash, request
from flask_login import login_user,logout_user,login_required,current_user
from app.utils import save_picture

from app.patient.forms import PatientLoginForm, PatientRegistrationForm, PatientProfileUpdateForm,PatientGetResetLinkForm,PatientResetPasswordForm

from app.patient import bp

from app.extentions import db, bcrypt
from app.models import UserModel, PatientModel
from app.utils import generate_confirmation_token, confirm_token,send_email, email_verified


@bp.route('/',methods=["GET", "POST"])
def index():
    if current_user.is_authenticated and current_user.role == "patient":
        return redirect(url_for('patient.dashboard')) 
    return redirect(url_for("patient.login"))

@bp.route('/register',methods=["GET","POST"])
def register():
    if current_user.is_authenticated and current_user.role == "patient":
        return redirect(url_for('patient.dashboard'))
    
    form = PatientRegistrationForm()

    if form.validate_on_submit():
        user = UserModel(full_name=form.full_name.data, email=form.email.data,password=form.password.data,role="patient")
        db.session.add(user)
        db.session.commit()

        flash(f'Account created for {form.email.data}! You can login now.', 'green')
        return redirect(url_for('patient.login'))
    
    return render_template('patient/registration.html' , title = 'Patient Register',form=form)

@bp.route('/login',methods=["GET", "POST"])
@email_verified
def login():
    if current_user.is_authenticated and current_user.role == "patient":
        return redirect(url_for('patient.dashboard'))
    
    form = PatientLoginForm()
    if form.validate_on_submit():
        user = UserModel.query.filter_by(email=form.email.data).first()
        if user and user.role == "patient" and bcrypt.check_password_hash(user.password,form.password.data):
            login_user(user)
            return redirect(url_for("patient.dashboard"))
        else:
            flash('Invalid Password. Please verify your password and try again!', 'red')
    return render_template('patient/login.html', title = 'Patient Login',form = form)

@bp.route('/verify')
@login_required
def verify():
    # print(type(current_user.token_sent_on))
    if current_user.confirmed:
        flash(f'Your email is already verified.', 'green')
        return redirect(url_for('patient.dashboard'))
    
    elif not current_user.token_sent_on or datetime.datetime.now() - current_user.token_sent_on  > datetime.timedelta(seconds=3600):
        token = generate_confirmation_token(current_user.email)
        confirm_url = url_for('patient.confirm', token=token, _external=True)
        html = render_template('mail-layout.html',type="email_verification", url=confirm_url)
        subject = "Please confirm your email"
        send_email(current_user.email, subject, html)
        current_user.token_sent_on = datetime.datetime.now()
        db.session.commit()
        flash(f'Your email is not verified. Please verify your email address.', 'red')
        return render_template('patient/verify.html', title = 'Patient Verification')

    flash(f'Email verification link is already been sent. Please follow the link to verify your email.', 'yellow')
    return render_template('patient/verify.html', title = 'Patient Verification')
    
@bp.route('/confirm/<token>',methods=["GET","POST"])
@login_required
def confirm(token):
    try:
        email = confirm_token(token)
        user = UserModel.query.filter_by(email=email).first_or_404()
        # print(email)
    except:
        flash('The confirmation link is invalid or has expired.', 'red')
        return redirect(url_for('patient.verify'))
    
    if user.confirmed:
        flash('Account already confirmed.', 'green')
    else:
        user.is_confirmed()
        db.session.commit()
        flash('You have confirmed your account. Thanks!', 'green')
    return redirect(url_for('patient.dashboard'))

@bp.route('/reset', methods=["GET", "POST"])
def get_reset_link():

    form = PatientGetResetLinkForm()
    if form.validate_on_submit():
        email = form.email.data
        token = generate_confirmation_token(email)
        confirm_url = url_for('patient.reset_password', token=token, _external=True)
        html = render_template('mail-layout.html',type="password_reset", url=confirm_url)
        subject = "Password Reset"
        send_email(email, subject, html)
        flash('Password reset link haas been shared to registerd email. Please follow the link to reset your password.', 'green')
        # patient = UserModel.query.filter_by(email=form.email.data).first()
        return redirect(url_for('patient.login')) 
    
    return render_template('patient/resetlink.html', title = 'Patient Reset',form = form)

@bp.route('/resetpassword/<token>',methods=["GET","POST"])
def reset_password(token):
    form = PatientResetPasswordForm()
    try:
        email = confirm_token(token)
        user = UserModel.query.filter_by(email=email).first_or_404()
    except:
        flash('Invalid Operation', 'yellow')
        return redirect(url_for('patient.login'))
    
    if form.validate_on_submit():
        user.change_password(form.password.data)
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'green')
        return redirect(url_for('patient.login'))
    return render_template('patient/resetpassword.html', tilte= 'Patient password Reset', form =form)

@bp.route('/logout')
def logout():
    logout_user()
    return redirect(url_for("patient.login"))

@bp.route('/dashboard')
@login_required
@email_verified
def dashboard():

    patientprofile = PatientModel.query.filter_by(user_id=current_user.id).first()

    if not patientprofile:
        flash(f'Welcome {current_user.full_name}! Please complete your profile first.', 'green')
        return redirect(url_for("patient.profile"))
    
    flash(f'Welcome {current_user.full_name}!', 'green')


    return render_template('patient/dashboard.html' , title = 'Dashboard')

@bp.route('/account')
@login_required
@email_verified
def account():
    if current_user.is_authenticated and current_user.role == "patient":
        return render_template('patient/account.html' , title = 'Account', user=f"{current_user.full_name}  ({current_user.email})")
    return redirect(url_for('patient.login')) 

@bp.route('/profile',methods=["GET", "POST"])
@login_required
@email_verified
def profile():
    if current_user.is_authenticated and current_user.role == "patient":
        form  =PatientProfileUpdateForm()

        patient_profile = PatientModel.query.filter_by(user_id=current_user.id).first()

        if patient_profile:

            if request.method == "GET":
                form.phone_no.data = patient_profile.phone_no
                form.age.data = patient_profile.age
                form.address.data = patient_profile.address
                form.gender.data = patient_profile.gender
                form.height.data = patient_profile.height
                form.weight.data = patient_profile.weight

            elif form.validate_on_submit():
                if form.picture.data:
                    picture_file = save_picture(form.picture.data)
                    current_user.image_file = picture_file

                patient_profile.phone_no = form.phone_no.data
                patient_profile.age = form.age.data
                patient_profile.address = form.address.data
                patient_profile.gender = form.gender.data
                patient_profile.height = form.height.data
                patient_profile.weight = form.weight.data 
                db.session.commit()
                flash(f'Profile has been updated for {current_user.full_name}.', 'green')
            
            return render_template('patient/profile.html' , form= form, title = 'Profile')

        if form.validate_on_submit():
            if form.picture.data:
                current_user.image_file = save_picture(form.picture.data)

            new_patient_profile = PatientModel(user_id=current_user.id, phone_no=form.phone_no.data, age=form.age.data, gender=form.gender.data,address=form.address.data, height=form.height.data, weight=form.weight.data)

            db.session.add(new_patient_profile)
            db.session.commit()

            flash(f'Profile has been updated for {current_user.email}.', 'green')
            return redirect(url_for('patient.dashboard'))
        
        return render_template('patient/profile.html', form= form, title = 'Profile')
    else:
        return redirect(url_for("doctor.login"))
    

app/templates/patient/account.html
{% extends "account-layout.html" %}

app/templates/patient/dashboard.html
{% extends "account-layout.html" %}
{% block contents %}
    



<!-- final -->

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container mx-auto">

    <div class="lg:w-full py-20 mx-auto flex flex-wrap">

        
        <div class="lg:w-1/2 w-full lg:pr-5 lg:pl-5  lg:py-5 lg:mb-0 flex flex-wrap">
            <div class="lg:w-1/5 lg:mt-2"> 
                <img class=" rounded-full w-24 h-24 object-cover object-center" src="{{ url_for('static', filename='doc3.jpg') }}" alt="Doctor's Image">
            </div>
            <div class="ml-auto lg:w-4/5"> 
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-2">Dr. Rohit Jain</h1>
                <h2 class="text title-font text-gray-700 tracking-widest">OPHTHALMOLOGIST | 3 Years Exp</h2>
                <p class="leading-relaxed mt-2 mb-2">Availibility: MON, TUE, WED, THU, FRI</p>
                <div class="flex border-t border-gray-200 py-2">
                    <span><img width="20" height="20" src="{{ url_for('static', filename='education.png') }}" alt="marker--v1"/></span>
                    <span class="ml-5 text-gray-900">MBBS, MS(OPHTHALMOLOGY)</span>
                </div>
                <div class="flex border-t border-gray-200 py-2">
                    <span><img width="20" height="20" src="{{ url_for('static', filename='chat.png') }}" alt="marker--v1"/></span>
                    <span class="ml-5 text-gray-900">English, Hindi, Gujarati</span>
                </div>
                <div class="flex border-t border-b mb-4 border-gray-200 py-2">
                    <span><img width="20" height="20" src="{{ url_for('static', filename='location2.png') }}" alt="marker--v1"/></span>
                    <span class="ml-5 text-gray-900">402, Nakshtra-5, Ahmedabad</span>
                </div>
                <div class="flex">
                    <span class="title-font font-medium text-2xl text-gray-900">₹ 1000.00</span>
                    <button class="flex ml-auto text-white bg-green-500 border-0 py-2 px-6 focus:outline-none hover:bg-green-600 rounded">Book Appointment</button>
                    <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
                    <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                        <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
                    </svg>
                    </button>
                </div>
            </div>
        </div>
        <!-- <img alt="ecommerce" class="lg:w-1/3 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400"> -->


        <div class="lg:w-1/2 w-full lg:pr-5 lg:pl-5  lg:py-5 lg:mb-0 flex flex-wrap">
            <div class="lg:w-1/5 lg:mt-2"> 
                <img class=" rounded-full w-24 h-24 object-cover object-center" src="{{ url_for('static', filename='doc2.jpg') }}" alt="Doctor's Image">
            </div>
            <div class="ml-auto lg:w-4/5"> 
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-2">Dr. Aarohi Tyagi</h1>
                <h2 class="text title-font text-gray-700 tracking-widest">OPHTHALMOLOGIST | 10 Years Exp</h2>
                <p class="leading-relaxed mt-2 mb-2">Availibility: MON, TUE, WED, THU, FRI</p>
                <div class="flex border-t border-gray-200 py-2">
                    <span><img width="20" height="20" src="{{ url_for('static', filename='education.png') }}" alt="marker--v1"/></span>
                    <span class="ml-5 text-gray-900">MBBS, MS(OPHTHALMOLOGY)</span>
                </div>
                <div class="flex border-t border-gray-200 py-2">
                    <span><img width="20" height="20" src="{{ url_for('static', filename='chat.png') }}" alt="marker--v1"/></span>
                    <span class="ml-5 text-gray-900">English, Hindi, Gujarati</span>
                </div>
                <div class="flex border-t border-b mb-4 border-gray-200 py-2">
                    <span><img width="20" height="20" src="{{ url_for('static', filename='location2.png') }}" alt="marker--v1"/></span>
                    <span class="ml-5 text-gray-900">Kanan Multispeciality Hospital, Naroda, Ahmedabad</span>
                </div>
                <div class="flex">
                    <span class="title-font font-medium text-2xl text-gray-900">₹ 1400.00</span>
                    <button class="flex ml-auto text-white bg-green-500 border-0 py-2 px-6 focus:outline-none hover:bg-green-600 rounded">Book Appointment</button>
                    <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
                    <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                        <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
                    </svg>
                    </button>
                </div>
            </div>
        </div>




      </div>
    </div>
  </section>

  <!-- End -->





  {% endblock %}

app/templates/patient/doctordescription.html
{% extends "account-layout.html" %}
{% block contents %}
    



<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">BRAND NAME</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">Animated Night Hill Illustrations</h1>
          <div class="flex mb-4">
            <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Description</a>
            <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Reviews</a>
            <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Details</a>
          </div>
          <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Color</span>
            <span class="ml-auto text-gray-900">Blue</span>
          </div>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Size</span>
            <span class="ml-auto text-gray-900">Medium</span>
          </div>
          <div class="flex border-t border-b mb-6 border-gray-200 py-2">
            <span class="text-gray-500">Quantity</span>
            <span class="ml-auto text-gray-900">4</span>
          </div>
          <div class="flex">
            <span class="title-font font-medium text-2xl text-gray-900">$58.00</span>
            <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Button</button>
            <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
              <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
              </svg>
            </button>
          </div>
        </div>
        <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
      </div>
    </div>
  </section>

  {% endblock %}

app/templates/patient/login.html
{% extends "login-layout.html" %}

{% block form %}
  

<div class="lg:w-2/6 md:w-1/2 bg-gray-100 rounded-lg p-8 flex flex-col md:ml-auto w-full mt-10 md:mt-0">
  <h2 class="text-gray-900 text-lg font-medium title-font mb-4">Patient's Login</h2>

  <!-- WTF-form templating starts   -->

  <form method="POST"action="">
    {{form.hidden_tag()}}
    <!-- Email validation check and Email input field -->
    <div class="relative mb-4">
      {{form.email.label(class="leading-7 text-sm text-gray-600")}}
      {% if form.email.errors %}
        {{form.email(class="w-full bg-white rounded border border-gray-300 focus:border-green-500 focus:ring-2 focus:ring-green-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out")}}
        <div>
          {% for error in form.email.errors %}
          <span class="form-control text-red-500 text-sm"> {{error}} </span>
          {% endfor %}
        </div>
        {% else %}
          {{form.email(class="w-full bg-white rounded border border-gray-300 focus:border-green-500 focus:ring-2 focus:ring-green-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out")}}
      {% endif %}
    </div>

    <!-- Passsword input field -->
    <div class="relative mb-2">
      {{ form.password.label(class="leading-7 text-sm text-gray-600") }}
      {{ form.password(class="w-full bg-white rounded border border-gray-300 focus:border-green-500 focus:ring-2 focus:ring-green-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out") }}
    </div>

    <!-- Reset Password Link -->
    <div class="mb-2 text-right">
      <a href="{{ url_for('patient.get_reset_link' )}}" class="text-green-600 focus:outline-none focus:underline hover:underline">Reset Password</a>
    </div>

    <!-- Form submit button -->
    {{form.submit(class="text-white w-full bg-green-500 border-0 mb-4 py-2 px-8 focus:outline-none hover:bg-green-600 rounded text-lg")}}
  </form>

  <!-- WTF-form templating ends   -->
    <hr>
    <!-- <p class="text-s text-gray-500 mt-4">New to EasyVisit?..</p> -->
    <a href="{{ url_for('patient.register' )}}">
      <button class="text-green-500 w-full border-2 border-green-500 mt-3 py-2 px-8 focus:outline-none hover:bg-green-100 rounded text-lg">New Patient? Register here.</button>
    </a>  
</div>
{% endblock form %}

<!-- Home - Patient Login Content Ends -->

app/templates/patient/profile.html
{% extends "account-layout.html" %}

<!-- Patient Registration Content Starts -->
{% block contents %}
<section class="text-gray-600 body-font">
  <div class="container px-5 py-10 mx-auto flex flex-wrap items-center">
    <!-- <div class="lg:w-2/6 md:w-1/2 bg-gray-100 rounded-lg p-8 flex flex-col md:ml-auto w-full mt-10 md:mt-0"> -->
    <div class="mt-10 mx-auto flex w-full flex-col rounded-lg bg-gray-100 p-8 md:ml-auto md:mt-0 md:w-1/2 lg:w-1/2">
      <h2 class="text-gray-900 text-lg font-medium title-font mb-4">Patient's Profile</h2>

      <!-- Registration Form Starts -->
      <form method="POST" action="", enctype="multipart/form-data">
        {{form.hidden_tag()}}

        {% for field in form%}
        {% if (field.label.text != "Update Profile") and (field.label.text!="CSRF Token")%}
          
        
          <div class="relative mb-4">
            <label class="leading-7 text-sm text-gray-600" for="{{ field.id }}">{{ field.label.text }}:</label>
            {% if field.errors %}
              {{ field(class="w-full bg-white rounded border border-gray-300 focus:border-red-500 focus:ring-2 focus:ring-red-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out") }}
              <div> 
              {% for error in field.errors %}
                <span class="form-control text-red-500 text-sm">{{ error }}</span>
              {% endfor %}
              </div>
            {% else %}
              {{ field(class="w-full bg-white rounded border border-gray-300 focus:border-red-500 focus:ring-2 focus:ring-red-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out") }}
            {% endif %}
          </div>
        {% endif %}
        {% endfor %}

        <!-- Submit Button -->
        <div class=" pt-5">
        {{ form.submit(class="text-white w-full bg-green-500 border-0 mb-4 py-2 px-8 focus:outline-none hover:bg-green-600 rounded text-lg") }}
      </div>
      </form>
      <!-- Registration Form Ends -->

    </div>
  </div>
</section>

{% endblock contents %}
<!-- Patient Registration Content Ends -->

app/templates/patient/resetlink.html
{% extends "login-layout.html" %}

{% block form %}
  

    <div class="lg:w-2/6 md:w-1/2 bg-gray-100 rounded-lg p-8 flex flex-col md:ml-auto w-full mt-10 md:mt-0">
      <h2 class="text-gray-900 text-lg font-medium title-font mb-4">Get Passsword Reset Link</h2>

      <!-- WTF-form templating starts   -->

      <form method="POST"action="">
        {{form.hidden_tag()}}
        <!-- Email validation check and Email input field -->
        <div class="relative mb-4">
          {{form.email.label(class="leading-7 text-sm text-gray-600")}}
          {% if form.email.errors %}
            {{form.email(class="w-full bg-white rounded border border-gray-300 focus:border-green-500 focus:ring-2 focus:ring-green-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out")}}
            <div>
              {% for error in form.email.errors %}
              <span class="form-control text-red-500 text-sm"> {{error}} </span>
              {% endfor %}
            </div>
            {% else %}
              {{form.email(class="w-full bg-white rounded border border-gray-300 focus:border-green-500 focus:ring-2 focus:ring-green-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out")}}
          {% endif %}
        </div>

        <!-- Form submit button -->
        {{form.submit(class="text-white w-full bg-green-500 border-0 mb-4 py-2 px-8 focus:outline-none hover:bg-green-600 rounded text-lg")}}
      </form>
 
    </div>
{% endblock form %}

app/templates/patient/verify.html
{% extends 'account-layout.html' %}

{% block contents %}
    
{% endblock %}