app/models/doctor.py
from app.extentions import db

from flask_sqlalchemy import SQLAlchemy
import json
from app.models import UserModel


class DoctorModel(db.Model):
    __tablename__ = "doctors"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), unique=True)
    # image_file = db.Column(db.String(20), nullable=False, default='default.jpg')

    # id = db.Column(db.Integer, db.ForeignKey('users.id'), primary_key=True)
    phone_no = db.Column(db.String(15), nullable=False)
    speciality = db.Column(db.String(100),nullable=False)
    qualification = db.Column(db.String(100),nullable=False)
    experience = db.Column(db.Integer,nullable=False)
    languages = db.Column(db.String)
    address = db.Column(db.String(255), nullable=False)
    city = db.Column(db.String(100), nullable=False)
    
    def __init__(self,user_id,phone_no,speciality,qualification,experience,languages,address,city):
        self.user_id = user_id
        self.phone_no = phone_no
        self.speciality = speciality
        self.qualification = qualification
        self.experience = experience
        self.languages = json.dumps(languages)
        self.address = address
        self.city = city


    def __repr__(self):
        return f"<Doctor {self.name}>"

    def set_languages(self, languages):
        self.languages = json.dumps(languages)

    def get_languages(self):
        return json.loads(self.languages) if self.languages else []

    # __mapper_args__ = {
    #     'polymorphic_identity': 'doctor'
    # }

app/doctor/forms.py
import string
from flask_wtf import FlaskForm
from wtforms import BooleanField, FieldList, MultipleFileField, SelectMultipleField, StringField,PasswordField,SubmitField,IntegerField,SelectField, TextAreaField, TimeField
from flask_wtf.file import FileField, FileAllowed
from wtforms.validators import DataRequired,Length, Email ,EqualTo,Regexp, ValidationError,NumberRange,InputRequired

from wtforms.widgets import CheckboxInput, ListWidget
from flask_login import current_user
from app.models import DoctorModel,UserModel

from app.doctor.utils import doctor_specialties, indian_languages, indian_cities, week_days


class MultiCheckboxField(SelectMultipleField):
    widget = ListWidget(prefix_label=False)
    option_widget = CheckboxInput()

class DoctorLoginForm(FlaskForm):
    email = StringField("Email",validators =[DataRequired(), Email()])
    password = PasswordField("Password",validators=[DataRequired(),Length(min=2, max=20)])
    submit = SubmitField("Login")

class DoctorRegistrationForm(FlaskForm):
    full_name = StringField("Full Name",
                           validators=[DataRequired(), Length(min=2, max=40)])
    # phone_number = StringField('Phone Number', validators=[DataRequired(),Length(min=10, max=10, message='Mobile number must be 10 digits long'),
    #                                                         Regexp(r'^[6789]\d{9}$', message='Invalid mobile number format')])
    email = StringField("Email",validators =[DataRequired(), Email()])
    password = PasswordField("Password",validators=[DataRequired(),Length(min=2, max=20)])
    confirm_password = PasswordField('Confirm Password',
                                     validators=[DataRequired(), EqualTo('password')])

    submit = SubmitField("Sign Up")

    def validate_email(self,email):
        doctor = UserModel.query.filter_by(email=email.data,role="doctor").first()
        if doctor:
            raise ValidationError("Doctor with this email is already registered.")



## Patient Profile Update Form
class DoctorProfileUpdateForm(FlaskForm):
    #mandatory fields
    picture = FileField('Profile Picture', validators=[FileAllowed(['jpg', 'png'])])

    phone_no = StringField('Phone Number', validators=[DataRequired(),Length(min=10, max=10, message='Mobile number must be 10 digits long'),Regexp(r'^[6789]\d{9}$', message='Invalid mobile number format')])

    speciality = SelectField("Speciality",choices=[(i,i) for i in doctor_specialties],validators=[DataRequired()])

    qualification = StringField("Qualification",validators=[DataRequired(), Length(min=2, max=80)])
    experience = IntegerField("Experience")
    languages = SelectMultipleField("Languages (press 'ctrl' for selecting multiple languages)",choices=[(i,i) for i in indian_languages])
    
    address = TextAreaField("Adress",validators=[DataRequired(),Length(max=200)])
    city = SelectField("City",choices=[(i,i) for i in indian_cities],validators=[DataRequired()])

    submit = SubmitField("Update Profile")


class DoctorGetResetLinkForm(FlaskForm):
    email = StringField("Email",validators =[DataRequired(), Email()])
    submit = SubmitField("Get Password Reset Link")
    
    # Emaiil validation in database
    def validate_email(self,email):
        doctor = UserModel.query.filter_by(email=email.data,role="doctor").first()
        if not doctor:
            raise ValidationError("Doctor with this email doesn't exist.")


class DoctorResetPasswordForm(FlaskForm):
    password = PasswordField("Password",validators=[DataRequired(),Length(min=2, max=20)])
    confirm_password = PasswordField('Confirm Password',validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField("Reset Password")


## Patient Profile Update Form
    
# class SelectMultipleFieldWithCheckboxes(SelectMultipleField):
#     widget = widgets.ListWidget(prefix_label=False)
#     option_widget = widgets.CheckboxInput()




    # picture = FileField('Profile Picture', validators=[FileAllowed(['jpg', 'png'])])

    # phone_no = StringField('Phone Number', validators=[DataRequired(),Length(min=10, max=10, message='Mobile number must be 10 digits long'),Regexp(r'^[6789]\d{9}$', message='Invalid mobile number format')])

    # speciality = SelectField("Speciality",choices=[(i.lower(),i) for i in doctor_specialties],validators=[DataRequired()])
    # qualification = StringField("Qualification",validators=[DataRequired(), Length(min=2, max=50)])
    # languages = MultiCheckboxField("Languages (press 'ctrl' for selecting multiple languages)",choices=[(i.lower(),i) for i in indian_languages])
    # experience = IntegerField("Experience")
    # address = TextAreaField("Adress",validators=[DataRequired(),Length(max=200)])
    # city = SelectField("City",choices=[(i.lower(),i) for i in indian_cities],validators=[DataRequired()])

class DoctorTestForm(FlaskForm):
        # Define choices for time selection dropdowns with 30-minute intervals
    time_choices_30_minutes = [(f'{hour:02}:{minute:02}', f'{hour:02}:{minute:02}') for hour in range(0, 24) for minute in range(0, 60, 30)]

    # Dropdown for start time selection with 30-minute intervals
    start_time = SelectField('Start Time', choices=time_choices_30_minutes, validators=[InputRequired()])

    # Dropdown for end time selection with 30-minute intervals
    end_time = SelectField('End Time', choices=time_choices_30_minutes, validators=[InputRequired()])
    # start_time = TimeField('Start Time', validators=[InputRequired()])
    # end_time = TimeField('End Time', validators=[InputRequired()])

    duration_choices = [(15, '15'), (30, '30'), (45, '45'), (60, '60')]
    duration = SelectField('Consultation Duration (in minutes)', choices=duration_choices, coerce=int, validators=[InputRequired()])
    # duration = IntegerField('Duration (in minutes)', validators=[InputRequired(), NumberRange(min=1)])
    days = MultiCheckboxField('Select Days', choices=[(i[:3],i) for i in week_days])
    submit = SubmitField("Update Profile")

app/doctor/__init__.py
import imp
from flask import Blueprint

bp = Blueprint("doctor",__name__,)

from app.doctor import routes

app/doctor/routes.py
import datetime
import imp
import json
from pydoc import doc
from flask import Flask,redirect,render_template,url_for,flash,request
from flask_login import login_user,logout_user,login_required, current_user

from app.doctor.forms import DoctorLoginForm, DoctorRegistrationForm,DoctorProfileUpdateForm,DoctorGetResetLinkForm,DoctorResetPasswordForm,DoctorTestForm
from app.doctor import bp
from app.utils import save_picture

from app.extentions import db, bcrypt
from app.models import UserModel, DoctorModel
from app.utils import generate_confirmation_token, confirm_token,send_email, email_verified


@bp.route('/',methods=["GET", "POST"])
def index():
    if current_user.is_authenticated and current_user.role == "doctor":
            return redirect(url_for('doctor.dashboard')) 
    return redirect(url_for("doctor.login"))

@bp.route('/register',methods=["GET","POST"])
def register():

    if current_user.is_authenticated and current_user.role == "doctor":
        return redirect(url_for('doctor.dashboard'))
    
    form = DoctorRegistrationForm()

    if form.validate_on_submit():
        # print(form.data, "validated on front end")
        # hashed_password = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user = UserModel(full_name=form.full_name.data, email=form.email.data,password=form.password.data,role="doctor")
        db.session.add(user)
        db.session.commit()
 
        flash(f'Account created for {form.email.data}! You can login now.', 'green')
        return redirect(url_for('doctor.login'))
    
    return render_template('doctor/registration.html' , title = 'Doctor Register',form=form)

@bp.route('/login',methods=["GET", "POST"])
@email_verified
def login():
    # print(current_user)
    if current_user.is_authenticated and current_user.role == "doctor":
        return redirect(url_for('doctor.dashboard'))
    
    form = DoctorLoginForm()
    if form.validate_on_submit():
        doctor = UserModel.query.filter_by(email=form.email.data).first()
        if doctor and doctor.role == "doctor" and bcrypt.check_password_hash(doctor.password,form.password.data):
            login_user(doctor)
            return redirect(url_for("doctor.dashboard"))
        else:
            flash('Invalid Password. Please verify your password and try again!', 'red')
    return render_template('doctor/login.html', title = 'Doctor Login', form = form)

@bp.route('/verify')
@login_required
def verify():
    # print(type(current_user.token_sent_on))
    if current_user.confirmed:
        flash(f'Your email is already verified.', 'green')
        return redirect(url_for('doctor.dashboard'))
    
    elif not current_user.token_sent_on or datetime.datetime.now() - current_user.token_sent_on  > datetime.timedelta(seconds=3600):
        token = generate_confirmation_token(current_user.email)
        confirm_url = url_for('doctor.confirm', token=token, _external=True)
        html = render_template('mail-layout.html',type="email_verification", url=confirm_url)
        subject = "Please confirm your email"
        send_email(current_user.email, subject, html)
        current_user.token_sent_on = datetime.datetime.now()
        db.session.commit()
        flash(f'Your email is not verified. Please verify your email address.', 'red')
        return render_template('doctor/verify.html', title = 'doctor Verification')

    flash(f'Email verification link is already been sent. Please follow the link to verify your email.', 'yellow')
    return render_template('doctor/verify.html', title = 'doctor Verification')

@bp.route('/confirm/<token>',methods=["GET","POST"])
@login_required
def confirm(token):
    try:
        email = confirm_token(token)
        user = UserModel.query.filter_by(email=email).first_or_404()
        # print(email)
    except:
        flash('The confirmation link is invalid or has expired.', 'red')
        return redirect(url_for('doctor.verify'))
    
    if user.confirmed:
        flash('Account already confirmed.', 'green')
    else:
        user.is_confirmed()
        db.session.commit()
        flash('You have confirmed your account. Thanks!', 'green')
    return redirect(url_for('doctor.dashboard'))

@bp.route('/reset', methods=["GET", "POST"])
def get_reset_link():

    form = DoctorGetResetLinkForm()
    if form.validate_on_submit():
        email = form.email.data
        token = generate_confirmation_token(email)
        confirm_url = url_for('doctor.reset_password', token=token, _external=True)
        html = render_template('mail-layout.html',type="password_reset", url=confirm_url)
        subject = "Password Reset"
        send_email(email, subject, html)
        flash('Password reset link haas been shared to registerd email. Please follow the link to reset your password.', 'green')
        # doctor = UserModel.query.filter_by(email=form.email.data).first()
        return redirect(url_for('doctor.login')) 
    
    return render_template('doctor/resetlink.html', title = 'Doctor Reset',form = form)

@bp.route('/resetpassword/<token>',methods=["GET","POST"])
def reset_password(token):
    form = DoctorResetPasswordForm()
    try:
        email = confirm_token(token)
        user = UserModel.query.filter_by(email=email).first_or_404()
    except:
        flash('Invalid Operation', 'yellow')
        return redirect(url_for('doctor.login'))
    
    if form.validate_on_submit():
        user.change_password(form.password.data)
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'green')
        return redirect(url_for('doctor.login'))
    return render_template('doctor/resetpassword.html', tilte= 'Doctor password Reset', form =form)

@bp.route('/logout')
def logout():
    logout_user()
    return redirect(url_for("doctor.login"))

@bp.route('/dashboard')
@login_required
@email_verified
def dashboard():
    doctorprofile = DoctorModel.query.filter_by(user_id=current_user.id).first()
    if not doctorprofile:
        flash(f'Welcome Dr. {current_user.full_name}! Please complete your profile first.', 'green')
        return redirect(url_for("doctor.profile"))
    flash(f'Welcome Dr. {current_user.full_name}!', 'green')

    return render_template('doctor/dashboard.html' , title = 'Dashboard')

@bp.route('/account')
@login_required
@email_verified
def account():
    if current_user.is_authenticated and current_user.role == "doctor":
        return render_template('doctor/account.html' , title = 'Account')
    return redirect(url_for("doctor.login"))

@bp.route('/profile',methods=["GET","POST"])
@login_required
@email_verified
def profile():
    if current_user.is_authenticated and current_user.role == "doctor":
        form = DoctorProfileUpdateForm()

        doctor_profile = DoctorModel.query.filter_by(user_id=current_user.id).first()

        if doctor_profile:
            print("in doc profile")
        # If Doctor's profile already exists and user loads the profile page, below condition will show the profile.
            if request.method == "GET":
                print("in get")
                form.phone_no.data = doctor_profile.phone_no
                form.speciality.data = doctor_profile.speciality
                form.qualification.data = doctor_profile.qualification
                form.experience.data = doctor_profile.experience
                form.languages.data = doctor_profile.get_languages()
                form.address.data = doctor_profile.address
                form.city.data = doctor_profile.city

            # If Doctor's profile already exists and user updates the profile page, below condition will update the Doctor's profile.
            elif form.validate_on_submit():
                if form.picture.data:
                    # print("in second loop")
                    picture_file = save_picture(form.picture.data)
                    current_user.image_file = picture_file
                # print("in elif")
                # print(form.qualification.data)
                doctor_profile.phone_no = form.phone_no.data
                doctor_profile.speciality = form.speciality.data
                doctor_profile.qualification = form.qualification.data
                doctor_profile.experience = form.experience.data
                doctor_profile.set_languages(form.languages.data)
                doctor_profile.address = form.address.data
                doctor_profile.city = form.city.data
                db.session.commit()
                flash(f'Profile has been updated for {current_user.full_name}.', 'green')
            
            return render_template('doctor/profile.html' , form= form, title = 'Profile')

        # If Doctor's profile doesn't exist and user fills the profile page, below condition will create the Doctor's profile.
        if form.validate_on_submit():
            # print("in lastprofile")
            if form.picture.data:
                current_user.image_file = save_picture(form.picture.data)
    
            print(form.qualification.data)
            new_doctor_profile = DoctorModel(user_id=current_user.id, phone_no=form.phone_no.data, speciality=form.speciality.data, qualification=form.qualification.data,experience=form.experience.data,languages = form.languages.data, address = form.address.data, city = form.city.data )

            db.session.add(new_doctor_profile)
            db.session.commit()

            flash(f'Profile has been updated for {current_user.full_name}.', 'green')
            return redirect(url_for('doctor.dashboard'))
        
        return render_template('doctor/profile.html' , form= form , title = 'Profile')
    else:
        return redirect(url_for("patient.login"))
    
@bp.route('/test',methods=["GET","POST"])
@login_required
@email_verified
def test():
    form = DoctorTestForm()
    if form.validate_on_submit():
        selected_days = json.dumps(form.days.data)
        start_time =  form.start_time.data
        

app/templates/doctor/account.html
{% extends "account-layout.html" %}

app/templates/doctor/dashboard.html
{% extends "account-layout.html" %}

app/templates/doctor/login.html
{% extends "login-layout.html" %}

{% block form %}


<div class="lg:w-2/6 md:w-1/2 bg-gray-100 rounded-lg p-8 flex flex-col md:ml-auto w-full mt-10 md:mt-0">
  <h2 class="text-gray-900 text-lg font-medium title-font mb-4">Doctor's Login</h2>

  <!-- WTF-form templating starts   -->
  <form method="POST"action="">
    {{form.hidden_tag()}}
    <!-- Email validation check and Email input field -->
    <div class="relative mb-4">
      {{form.email.label(class="leading-7 text-sm text-gray-600")}}
      {% if form.email.errors %}
        {{form.email(class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out")}}
        <div>
          {% for error in form.email.errors %}
          <span class="form-control text-red-500 text-sm"> {{error}} </span>
          {% endfor %}
        </div>
        {% else %}
          {{form.email(class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out")}}
      {% endif %}
    </div>

    <!-- Passsword input field -->
    <div class="relative mb-4">
      {{ form.password.label(class="leading-7 text-sm text-gray-600") }}
      {{ form.password(class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out") }}
    </div>

    <!-- Reset Password Link -->
    <div class="mb-2 text-right">
      <a href="{{ url_for('doctor.get_reset_link' )}}" class="text-indigo-600 focus:outline-none focus:underline hover:underline">Reset Password</a>
    </div>

    <!-- Form submit button -->
    {{form.submit(class="text-white w-full bg-indigo-500 border-0 mb-4 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg")}}
  </form>
  <!-- WTF-form templating ends   -->
    <hr>
    <!-- <p class="text-s text-gray-500 mt-4">New to EasyVisit?..</p> -->
    <a href="{{ url_for('doctor.register' )}}">
      <button class="text-indigo-500 w-full border-2 border-indigo-500 mt-3 py-2 px-8 focus:outline-none hover:bg-indigo-100 rounded text-lg">Want to join us? Register here.</button>
    </a>  
</div>
  {% endblock form %}
<!-- Home - Doctor Login Content Ends -->

app/templates/doctor/profile.html
{% extends "account-layout.html" %}

<!-- Doctor Profile Content Starts -->
{% block contents %}

<section class="text-gray-600 body-font">

  <div class="container px-5 py-10 mx-auto flex flex-wrap items-center">
  <!-- <div class="lg:w-2/6 md:w-1/2 bg-gray-100 rounded-lg p-8 flex flex-col md:ml-auto w-full mt-10 md:mt-0"> -->
    <div class="mt-10 mx-auto flex w-full flex-col rounded-lg bg-gray-100 p-8 md:ml-auto md:mt-0 md:w-1/2 lg:w-1/2">
      <h2 class="text-gray-900 text-lg font-medium title-font mb-4">Doctor's Profile</h2>

      <!-- Registration Form Starts -->
      <form method="POST" action="", enctype="multipart/form-data">
        {{form.hidden_tag()}}

        {% for field in form%}
        {% if (field.label.text != "Update Profile") and (field.label.text!="CSRF Token")%}
          
        
          <div class="relative mb-4">
            <label class="leading-7 text-sm text-gray-600" for="{{ field.id }}">{{ field.label.text }}:</label>
            {% if field.errors %}
              {{ field(class="w-full bg-white rounded border border-gray-300 focus:border-red-500 focus:ring-2 focus:ring-red-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out") }}
              <div> 
              {% for error in field.errors %}
                <span class="form-control text-red-500 text-sm">{{ error }}</span>
              {% endfor %}
              </div>
            {% else %}
              {{ field(class="w-full bg-white rounded border border-gray-300 focus:border-red-500 focus:ring-2 focus:ring-red-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out") }}
            {% endif %}
          </div>
        {% endif %}
        {% endfor %}

        <!-- Submit Button -->
        <div class=" pt-5">
        {{ form.submit(class="text-white w-full bg-green-500 border-0 mb-4 py-2 px-8 focus:outline-none hover:bg-green-600 rounded text-lg") }}
      </div>
      </form>
      <!-- Registration Form Ends -->

    </div>
  </div>
</section>

{% endblock contents %}
<!-- Patient Registration Content Ends -->

app/templates/doctor/registration.html
{% extends "layout.html" %}

<!-- Patient Registration Content Starts -->
{% block contents %}
<section class="text-gray-600 body-font">
  <div class="container px-5 py-10 mx-auto flex flex-wrap items-center">
    <!-- <div class="lg:w-2/6 md:w-1/2 bg-gray-100 rounded-lg p-8 flex flex-col md:ml-auto w-full mt-10 md:mt-0"> -->
    <div class="mt-10 mx-auto flex w-full flex-col rounded-lg bg-gray-100 p-8 md:ml-auto md:mt-0 md:w-1/2 lg:w-1/2">
      <h2 class="text-gray-900 text-lg font-medium title-font mb-4">Doctor Registration</h2>

      <!-- Registration Form Starts -->
      <form method="POST" action="">
        {{form.hidden_tag()}}

        <!-- Full Name -->

        {% for field in form%}
        {% if (field.label.text != "Sign Up") and (field.label.text!="CSRF Token")%}
          
        
          <div class="relative mb-4">
            <label class="leading-7 text-sm text-gray-600" for="{{ field.id }}">{{ field.label.text }}:</label>
            {% if field.errors %}
              {{ field(class="w-full bg-white rounded border border-gray-300 focus:border-red-500 focus:ring-2 focus:ring-red-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out") }}
              <div> 
              {% for error in field.errors %}
                <span class="form-control text-red-500 text-sm">{{ error }}</span>
              {% endfor %}
              </div>
            {% else %}
              {{ field(class="w-full bg-white rounded border border-gray-300 focus:border-red-500 focus:ring-2 focus:ring-red-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out") }}
            {% endif %}
          </div>
        {% endif %}
        {% endfor %}

        <!-- Submit Button -->
        <div class=" pt-5">
        {{ form.submit(class="text-white w-full bg-indigo-500 border-0 mb-4 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg") }}
      </div>
      </form>
      <!-- Registration Form Ends -->

    </div>
  </div>
</section>

{% endblock contents %}
<!-- Patient Registration Content Ends -->

app/templates/doctor/resetlink.html
{% extends "login-layout.html" %}

{% block form %}
  

    <div class="lg:w-2/6 md:w-1/2 bg-gray-100 rounded-lg p-8 flex flex-col md:ml-auto w-full mt-10 md:mt-0">
      <h2 class="text-gray-900 text-lg font-medium title-font mb-4">Get Passsword Reset Link</h2>

      <!-- WTF-form templating starts   -->

      <form method="POST"action="">
        {{form.hidden_tag()}}
        <!-- Email validation check and Email input field -->
        <div class="relative mb-4">
          {{form.email.label(class="leading-7 text-sm text-gray-600")}}
          {% if form.email.errors %}
            {{form.email(class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out")}}
            <div>
              {% for error in form.email.errors %}
              <span class="form-control text-red-500 text-sm"> {{error}} </span>
              {% endfor %}
            </div>
            {% else %}
              {{form.email(class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out")}}
          {% endif %}
        </div>

        <!-- Form submit button -->
        {{form.submit(class="text-white w-full bg-indigo-500 border-0 mb-4 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg")}}
      </form>
 
    </div>
{% endblock form %}

app/templates/doctor/resetpassword.html
{% extends 'login-layout.html' %}

{% block form %}
  

    <div class="lg:w-2/6 md:w-1/2 bg-gray-100 rounded-lg p-8 flex flex-col md:ml-auto w-full mt-10 md:mt-0">
      <h2 class="text-gray-900 text-lg font-medium title-font mb-4">Reset Your Password</h2>

      <!-- WTF-form templating starts   -->

      <form method="POST"action="">
        {{form.hidden_tag()}}
        <!-- Email validation check and Email input field -->
        <div class="relative mb-2">
            {{ form.password.label(class="leading-7 text-sm text-gray-600") }}
            {{ form.password(class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out") }}
        </div>

        <div class="relative mb-4">
            {{form.confirm_password.label(class="leading-7 text-sm text-gray-600")}}
            {% if form.confirm_password.errors %}
              {{form.confirm_password(class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out")}}
              <div>
                {% for error in form.confirm_password.errors %}
                <span> {{error}} </span>
                {% endfor %}
              </div>
              {% else %}
                {{form.confirm_password(class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out")}}
            {% endif %}
          </div>
  

        <!-- Form submit button -->
        {{form.submit(class="text-white w-full bg-indigo-500 border-0 mb-4 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg")}}
      </form>
 
    </div>
{% endblock form %}

app/templates/doctor/verify.html
{% extends 'account-layout.html' %}

{% block contents %}
    
{% endblock %}